name: "matrix-commit"
description: "A Github Action for sending messages to a Matrix Room."
branding:
  icon: "bell"
  color: "gray-dark"

inputs:
  homeserver:
    description: "Matrix Homeserver (https://matrix.org)"
    required: true
  username:
    description: "Matrix Username (user)"
    required: true
  access_token:
    description: "Matrix Access Token (syt_a3J...Ntg)"
    required: true
  room_id:
    description: "Matrix Room ID (!Stk...XbP:matrix.org)"
  message:
    description: "Message in Markdown format (# Commit Successful!)"

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    HOMESERVER: ${{ inputs.homeserver }}
    USERNAME: ${{ inputs.username }}
    ACCESS_TOKEN: ${{ inputs.access_token }}
    ROOM_ID: ${{ inputs.room_id }}
    MESSAGE: ${{ inputs.message }}
